server:
  port: 8080
spring:
  application:
    name: xiaoxinshu-gateway
  profiles:
    active: dev
logging:
  level:
    com.lilemy: info
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"