spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.37.130:3306/xiaoxinshu_interface
    username: root
    password: 123456
dubbo:
  registry:
    address: nacos://192.168.37.130:8848
    parameters.register-consumer-url: true
  protocol:
    port: 22225
  application:
    qos-port: 22226