server:
  port: 9204
  servlet:
    context-path: /api/interface
spring:
  application:
    name: xiaoxinshu-interface
  profiles:
    active: dev
logging:
  level:
    com.lilemy: info
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"