server:
  port: 9204
  servlet:
    context-path: /interface
spring:
  application:
    name: xiaoxinshu-interface
  profiles:
    active: dev
xiaoxinshu:
  client:
    access-key: d179dc0c911ac389c0cdf970471d842d
    secret-key: 773320702127c324956cac01bb82e783